trigger:
  - main

variables:
  imageName: 'k8sapp'
  acrLoginServer: 'k8sappacr.azurecr.io'
  kubernetesNamespace: 'default'

pool:
  name: 'default'

stages:

#Build and Push Docker Image to Azure Container Registry (ACR)
- stage: BuildAndPush
  displayName: 'Build and Push to ACR'
  jobs:
  - job: DockerBuild
    displayName: 'Build Docker Image'    
    steps:
    - task: Docker@2
      displayName: 'Build and push Docker image to ACR'
      inputs:
        containerRegistry: 'AzureContainerRegistryConnection'
        command: 'buildAndPush'
        repository: $(imageName)
        dockerfile: 'app/Dockerfile'
        buildContext: 'app'
        tags: |
          latest

#Deploy Infrastructure using Terraform
- stage: DeployInfrastructure
  displayName: 'Deploy Infrastructure via Terraform'
  dependsOn: BuildAndPush
  jobs:
    - job: Terraform
      displayName: 'Run Terraform'
      steps:
        - task: PowerShell@2
          displayName: 'Terraform Init'
          inputs:
            targetType: 'inline'
            workingDirectory: 'modules'
            script: |
              terraform -chdir=modules init

        - task: PowerShell@2
          displayName: 'Terraform Apply'
          inputs:
            targetType: 'inline'
            workingDirectory: 'modules'
            script: |
              terraform -chdir=modules apply -auto-approve

#Deploy Application to Azure Kubernetes Service (AKS)
- stage: DeployToAKS
  displayName: 'Deploy App to AKS'
  dependsOn: DeployInfrastructure
  jobs:       
    - job: DeployApp
      displayName: 'Deploy Kubernetes Manifests'
      steps: 
        - task: KubernetesManifest@1
          displayName: 'Deploy to AKS'
          inputs:
            action: deploy
            kubernetesServiceConnection: 'k8sapp-az'
            namespace: $(kubernetesNamespace)
            manifests: |
              k8s-manifests/deployment.yaml
              k8s-manifests/service.yaml
              